import OrdersAdmin, { type OrdersAdminConfig } from '../_OrdersAdmin'

const config: OrdersAdminConfig = {
  title: '일반주문 관리',
  subtitle: '일반 소비자 주문 접수 및 관리',
  tableName: 'general_orders',
  itemsTableName: 'general_order_items',
  customerField: 'customer_name',
  customerFallback: '고객',
  customerSearchPlaceholder: '🔍 고객명 / 연락처 / 주문번호',
  priceField: 'retail_price',
  paymentList: ['가상계좌', '현금', '카드', '외상'],
  registerGradient: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
  activeGradient: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
  trackingSaveGradient: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
  shadowColor: 'rgba(99,102,241,0.35)',
  focusRingClass: 'focus:ring-indigo-400',
  amountTextClass: 'text-indigo-600 dark:text-indigo-400',
  editTextClass: 'text-indigo-500',
  editBorderClass: 'border-indigo-200 dark:border-indigo-800',
  editBgClass: 'bg-indigo-50 dark:bg-indigo-900/20',
  addButtonClass: 'text-indigo-500',
  addButtonHoverClass: 'hover:text-indigo-600',
  addButtonBgClass: 'bg-indigo-50 dark:bg-indigo-900/20',
  addButtonBgHoverClass: 'hover:bg-indigo-100',
  viewEditButtonClass: 'flex-1 py-2.5 rounded-xl text-sm font-bold border-2 border-indigo-200 dark:border-indigo-800 text-indigo-600 dark:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-indigo-900/20 transition-colors',
  statRevenueColor: 'from-emerald-500 to-teal-500',
  totalBg: 'linear-gradient(135deg,rgba(99,102,241,0.08),rgba(139,92,246,0.08))',
  emptyIcon: '🛒',
  spinnerClass: 'border-3 border-indigo-500',
  listVariant: 'customer',
  showViewStatusChange: true,
  formTitle: '✨ 일반 주문 등록',
  formSubtitle: '일반 소비자 주문',
  formSectionTitle: '👤 고객 정보',
  formFields: [
    { label: '고객명 *', key: 'customer_name', placeholder: '예) 홍길동', col: 1 },
    { label: '연락처', key: 'contact', placeholder: '010-0000-0000', col: 1 },
    { label: '배송지 *', key: 'address', placeholder: '배송 주소를 입력해주세요', col: 2 },
  ],
  trackingHelpText: '송장 등록 시 손님이 마이페이지에서 실시간 배송조회를 할 수 있어요.',
  excelSheetName: '일반주문',
  excelFilePrefix: '일반주문',
  excelCustomerHeader: '고객명',
  excelIndentedRows: true,
  requireAddress: true,
  includeFadeStyle: true,
}

export default function GeneralOrdersPage() {
  return <OrdersAdmin config={config} />
}
