// 무료 상품 이미지 라이브러리 (온종일 AI 제품 이미지) — 종류별 그룹
// public/landing/img/ 에 배포됨. data.js에서 자동 생성(파일/카테고리 바뀌면 스크립트 재실행).
export type StockImage = { src: string; cat: string; group: string };

export const STOCK_IMAGES: StockImage[] = [
  { src: "/ai-images/food/bakery_baguette.webp", cat: "바게트", group: "베이커리" },
  { src: "/ai-images/food/bakery_bread.webp", cat: "우리밀 식빵", group: "베이커리" },
  { src: "/ai-images/food/bakery_cookie.webp", cat: "수제 쿠키 6입", group: "베이커리" },
  { src: "/ai-images/food/bakery_croissant.webp", cat: "버터 크루아상", group: "베이커리" },
  { src: "/ai-images/food/bakery_cupcake.webp", cat: "바닐라 컵케이크", group: "베이커리" },
  { src: "/ai-images/food/bakery_pretzel.webp", cat: "프레첼", group: "베이커리" },
  { src: "/ai-images/food/banchan_anchovy.webp", cat: "멸치볶음 200g", group: "반찬" },
  { src: "/ai-images/food/banchan_eomuk.webp", cat: "어묵볶음", group: "반찬" },
  { src: "/ai-images/food/banchan_geotjeori.webp", cat: "겉절이 500g", group: "반찬" },
  { src: "/ai-images/food/banchan_jangjorim.webp", cat: "장조림 300g", group: "반찬" },
  { src: "/ai-images/food/banchan_riceball.webp", cat: "주먹밥 세트", group: "반찬" },
  { src: "/ai-images/food/banchan_stew.webp", cat: "된장찌개 2인분", group: "반찬" },
  { src: "/ai-images/food/dairy_butter.webp", cat: "발효버터 200g", group: "유제품" },
  { src: "/ai-images/food/dairy_cheese.webp", cat: "수제 모짜렐라", group: "유제품" },
  { src: "/ai-images/food/dairy_icecream.webp", cat: "우유 아이스크림", group: "유제품" },
  { src: "/ai-images/food/dairy_milk.webp", cat: "유기농 우유 1L", group: "유제품" },
  { src: "/ai-images/food/dairy_pudding.webp", cat: "우유 푸딩 2입", group: "유제품" },
  { src: "/ai-images/food/dairy_yogurt.webp", cat: "플레인 요거트", group: "유제품" },
  { src: "/ai-images/food/food_egg.webp", cat: "유정란 10구", group: "유제품" },
  { src: "/ai-images/food/food_honey.webp", cat: "자연산 꿀 500g", group: "전통" },
  { src: "/ai-images/food/fruit_apple.webp", cat: "부사 사과 5kg", group: "과일" },
  { src: "/ai-images/food/fruit_grape.webp", cat: "샤인머스캣 1송이", group: "과일" },
  { src: "/ai-images/food/fruit_mango.webp", cat: "애플망고 2입", group: "과일" },
  { src: "/ai-images/food/fruit_peach.webp", cat: "복숭아 선물세트", group: "과일" },
  { src: "/ai-images/food/fruit_strawberry.webp", cat: "설향 딸기 1팩", group: "과일" },
  { src: "/ai-images/food/fruit_tangerine.webp", cat: "제주 감귤 3kg", group: "과일" },
  { src: "/ai-images/food/gourmet_cheeseplatter.webp", cat: "수입 치즈 플래터", group: "고메" },
  { src: "/ai-images/food/gourmet_chocolate.webp", cat: "싱글오리진 초콜릿", group: "고메" },
  { src: "/ai-images/food/gourmet_giftset.webp", cat: "프리미엄 선물세트", group: "고메" },
  { src: "/ai-images/food/gourmet_oliveoil.webp", cat: "엑스트라버진 올리브유", group: "고메" },
  { src: "/ai-images/food/gourmet_teaset.webp", cat: "프리미엄 티 세트", group: "고메" },
  { src: "/ai-images/food/gourmet_wine.webp", cat: "내추럴 와인", group: "고메" },
  { src: "/ai-images/food/meat_bacon.webp", cat: "베이컨 슬라이스", group: "축산" },
  { src: "/ai-images/food/meat_beef.webp", cat: "한우 등심 200g", group: "축산" },
  { src: "/ai-images/food/meat_chicken.webp", cat: "닭다리살 1kg", group: "축산" },
  { src: "/ai-images/food/meat_porkbelly.webp", cat: "삼겹살 600g", group: "축산" },
  { src: "/ai-images/food/meat_sausage.webp", cat: "수제 소시지 4입", group: "축산" },
  { src: "/ai-images/food/meat_striploin.webp", cat: "채끝 스테이크", group: "축산" },
  { src: "/ai-images/food/produce_broccoli.webp", cat: "브로콜리 2송이", group: "채소" },
  { src: "/ai-images/food/produce_carrot.webp", cat: "흙당근 1kg", group: "채소" },
  { src: "/ai-images/food/produce_garlic.webp", cat: "햇마늘 500g", group: "채소" },
  { src: "/ai-images/food/produce_mushroom.webp", cat: "생표고버섯 한 팩", group: "채소" },
  { src: "/ai-images/food/produce_spinach.webp", cat: "유기농 시금치 한 단", group: "채소" },
  { src: "/ai-images/food/produce_ssam.webp", cat: "모둠 쌈채소", group: "채소" },
  { src: "/ai-images/food/seafood_driedshrimp.webp", cat: "마른새우 200g", group: "수산" },
  { src: "/ai-images/food/seafood_hairtail.webp", cat: "손질 갈치 2마리", group: "수산" },
  { src: "/ai-images/food/seafood_myeongnan.webp", cat: "명란젓 300g", group: "수산" },
  { src: "/ai-images/food/seafood_oyster.webp", cat: "생굴 1kg", group: "수산" },
  { src: "/ai-images/food/seafood_prawn.webp", cat: "생새우 500g", group: "수산" },
  { src: "/ai-images/food/seafood_squid.webp", cat: "손질 오징어 3마리", group: "수산" },
  { src: "/ai-images/food/traditional_doenjang.webp", cat: "재래식 막된장 1kg", group: "전통" },
  { src: "/ai-images/food/traditional_giftset.webp", cat: "명절 선물세트", group: "전통" },
  { src: "/ai-images/food/traditional_gochujang.webp", cat: "태양초 고추장 500g", group: "전통" },
  { src: "/ai-images/food/traditional_kimchi.webp", cat: "포기김치 2kg", group: "전통" },
  { src: "/ai-images/food/traditional_makgeolli.webp", cat: "전통 막걸리", group: "전통" },
  { src: "/ai-images/food/traditional_tea.webp", cat: "국산 쌍화차", group: "전통" },
  { src: "/ai-images/life/backpack.webp", cat: "캔버스 백팩", group: "패션" },
  { src: "/ai-images/life/belt.webp", cat: "가죽 벨트", group: "액세서리" },
  { src: "/ai-images/life/bouquet.webp", cat: "시즌 꽃다발", group: "리빙" },
  { src: "/ai-images/life/bracelet.webp", cat: "체인 팔찌", group: "액세서리" },
  { src: "/ai-images/life/camera.webp", cat: "미러리스 카메라", group: "테크" },
  { src: "/ai-images/life/candle.webp", cat: "소이 캔들 · Dusk", group: "리빙" },
  { src: "/ai-images/life/candleholder.webp", cat: "캔들 홀더", group: "리빙" },
  { src: "/ai-images/life/cap.webp", cat: "코튼 6패널 캡", group: "패션" },
  { src: "/ai-images/life/charger.webp", cat: "무선 충전패드", group: "테크" },
  { src: "/ai-images/life/cleanser.webp", cat: "약산성 클렌징폼", group: "뷰티" },
  { src: "/ai-images/life/coat.webp", cat: "클래식 트렌치코트", group: "패션" },
  { src: "/ai-images/life/coffeebean.webp", cat: "스페셜티 원두 200g", group: "리빙" },
  { src: "/ai-images/life/cushion.webp", cat: "커버 쿠션팩트", group: "뷰티" },
  { src: "/ai-images/life/denim.webp", cat: "데님 팬츠", group: "패션" },
  { src: "/ai-images/life/diffuser.webp", cat: "리드 디퓨저 200ml", group: "리빙" },
  { src: "/ai-images/life/dress.webp", cat: "린넨 미디 원피스", group: "패션" },
  { src: "/ai-images/life/earbuds.webp", cat: "미니 버즈 무선이어폰", group: "테크" },
  { src: "/ai-images/life/earring.webp", cat: "골드 후프 귀걸이", group: "액세서리" },
  { src: "/ai-images/life/frame.webp", cat: "우드 액자", group: "리빙" },
  { src: "/ai-images/life/handcream.webp", cat: "시어버터 핸드크림", group: "뷰티" },
  { src: "/ai-images/life/keyboard.webp", cat: "무선 기계식 키보드", group: "테크" },
  { src: "/ai-images/life/knit.webp", cat: "케이블 니트 스웨터", group: "패션" },
  { src: "/ai-images/life/lipstick.webp", cat: "벨벳 매트 립스틱", group: "뷰티" },
  { src: "/ai-images/life/mascara.webp", cat: "볼륨 마스카라", group: "뷰티" },
  { src: "/ai-images/life/moodlamp.webp", cat: "무드 조명 램프", group: "리빙" },
  { src: "/ai-images/life/mouse.webp", cat: "무선 마우스", group: "테크" },
  { src: "/ai-images/life/mug.webp", cat: "세라믹 머그 320ml", group: "리빙" },
  { src: "/ai-images/life/necklace.webp", cat: "골드 펜던트 목걸이", group: "액세서리" },
  { src: "/ai-images/life/notebook.webp", cat: "하드커버 노트", group: "리빙" },
  { src: "/ai-images/life/perfume.webp", cat: "오 드 퍼퓸 50ml", group: "뷰티" },
  { src: "/ai-images/life/pillow.webp", cat: "린넨 쿠션", group: "리빙" },
  { src: "/ai-images/life/plant.webp", cat: "미니 식물 · 율마", group: "리빙" },
  { src: "/ai-images/life/ring.webp", cat: "골드 반지", group: "액세서리" },
  { src: "/ai-images/life/rug.webp", cat: "우븐 러그", group: "리빙" },
  { src: "/ai-images/life/scarf.webp", cat: "울 머플러", group: "패션" },
  { src: "/ai-images/life/serum.webp", cat: "글로우 세럼 30ml", group: "뷰티" },
  { src: "/ai-images/life/shirt.webp", cat: "옥스포드 셔츠", group: "패션" },
  { src: "/ai-images/life/shoulderbag.webp", cat: "미니 숄더백", group: "패션" },
  { src: "/ai-images/life/smartwatch.webp", cat: "스마트워치", group: "테크" },
  { src: "/ai-images/life/sneaker.webp", cat: "러너 로우 스니커즈", group: "패션" },
  { src: "/ai-images/life/speaker.webp", cat: "블루투스 스피커", group: "테크" },
  { src: "/ai-images/life/sunglasses.webp", cat: "아세테이트 셰이드", group: "액세서리" },
  { src: "/ai-images/life/sunscreen.webp", cat: "데일리 선크림", group: "뷰티" },
  { src: "/ai-images/life/tote.webp", cat: "헤비 캔버스 토트백", group: "패션" },
  { src: "/ai-images/life/tumbler.webp", cat: "보온 텀블러 500ml", group: "리빙" },
  { src: "/ai-images/life/vase.webp", cat: "세라믹 화병", group: "리빙" },
  { src: "/ai-images/life/wallet.webp", cat: "가죽 반지갑", group: "액세서리" },
  { src: "/ai-images/life/watch.webp", cat: "필드 워치 38mm", group: "액세서리" },
];

export const STOCK_GROUPS = ["전체","채소","수산","축산","베이커리","과일","유제품","반찬","전통","고메","패션","뷰티","리빙","테크","액세서리"] as const;
