import OrdersAdmin, { type OrdersAdminConfig } from '../_OrdersAdmin'

const config: OrdersAdminConfig = {
  title: '도매주문 관리',
  subtitle: '도매 거래처 주문 접수 및 관리',
  tableName: 'wholesale_orders',
  itemsTableName: 'wholesale_order_items',
  customerField: 'company_name',
  customerFallback: '거래처',
  customerSearchPlaceholder: '🔍 업체명 / 연락처 / 주문번호',
  priceField: 'wholesale_price',
  paymentList: ['가상계좌', '현금', '외상'],
  registerGradient: 'linear-gradient(135deg,#7c3aed,#6366f1)',
  activeGradient: 'linear-gradient(135deg,#7c3aed,#6366f1)',
  trackingSaveGradient: 'linear-gradient(135deg,#7c3aed,#6366f1)',
  shadowColor: 'rgba(124,58,237,0.35)',
  focusRingClass: 'focus:ring-violet-400',
  amountTextClass: 'text-violet-600 dark:text-violet-400',
  editTextClass: 'text-violet-500',
  editBorderClass: 'border-violet-200 dark:border-violet-800',
  editBgClass: 'bg-violet-50 dark:bg-violet-900/20',
  addButtonClass: 'text-violet-500',
  addButtonHoverClass: 'hover:text-violet-600',
  addButtonBgClass: 'bg-violet-50 dark:bg-violet-900/20',
  addButtonBgHoverClass: 'hover:bg-violet-100',
  viewEditButtonClass: 'flex-1 py-2.5 rounded-xl text-sm font-bold border-2 border-violet-200 dark:border-violet-800 text-violet-600 dark:text-violet-400 hover:bg-violet-50 dark:hover:bg-violet-900/20 transition-colors',
  statRevenueColor: 'from-violet-500 to-purple-600',
  totalBg: 'linear-gradient(135deg,rgba(124,58,237,0.08),rgba(99,102,241,0.08))',
  emptyIcon: '🏭',
  spinnerClass: 'border-2 border-violet-500',
  listVariant: 'company',
  showViewStatusChange: true,
  formTitle: '✨ 도매 주문 등록',
  formSubtitle: '도매 거래처 주문',
  formSectionTitle: '🏭 거래처 정보',
  formFields: [
    { label: '업체명 *', key: 'company_name', placeholder: '예) 목포 수산', col: 1 },
    { label: '연락처', key: 'contact', placeholder: '010-0000-0000', col: 1 },
    { label: '배송지', key: 'address', placeholder: '배송 주소', col: 2 },
  ],
  trackingHelpText: '송장 등록 시 거래처가 마이페이지에서 실시간 배송조회를 할 수 있어요.',
  excelSheetName: '도매주문',
  excelFilePrefix: '도매주문',
  excelCustomerHeader: '업체명',
  excelIndentedRows: true,
  requireAddress: false,
  includeFadeStyle: false,
}

export default function WholesalePage() {
  return <OrdersAdmin config={config} />
}
