import OrdersAdmin, { type OrdersAdminConfig } from '../_OrdersAdmin'

const config: OrdersAdminConfig = {
  title: '소매주문 관리',
  subtitle: '소매 고객 주문 접수 및 관리',
  tableName: 'retail_orders',
  itemsTableName: 'retail_order_items',
  customerField: 'customer_name',
  customerFallback: '고객',
  customerSearchPlaceholder: '🔍 고객명 / 연락처 / 주문번호',
  priceField: 'retail_price',
  paymentList: ['가상계좌', '현금', '카드', '외상'],
  registerGradient: 'linear-gradient(135deg,#14532d,#15803d)',
  activeGradient: 'linear-gradient(135deg,#14532d,#15803d)',
  trackingSaveGradient: 'linear-gradient(135deg,#14b8a6,#0d9488)',
  shadowColor: 'rgba(22,163,74,0.35)',
  focusRingClass: 'focus:ring-teal-400',
  amountTextClass: 'text-teal-600 dark:text-teal-400',
  editTextClass: 'text-teal-500',
  editBorderClass: 'border-teal-200 dark:border-teal-800',
  editBgClass: 'bg-teal-50 dark:bg-teal-900/20',
  addButtonClass: 'text-teal-500',
  addButtonHoverClass: 'hover:text-teal-600',
  addButtonBgClass: 'bg-teal-50 dark:bg-teal-900/20',
  addButtonBgHoverClass: 'hover:bg-teal-100',
  viewEditButtonClass: 'flex-1 py-2.5 rounded-xl text-sm font-bold border-2 border-teal-200 dark:border-teal-800 text-teal-600 dark:text-teal-400 hover:bg-teal-50 dark:hover:bg-teal-900/20 transition-colors',
  statRevenueColor: 'from-emerald-500 to-teal-500',
  totalBg: 'linear-gradient(135deg,rgba(22,163,74,0.08),rgba(21,128,61,0.08))',
  emptyIcon: '🏪',
  spinnerClass: 'border-2 border-teal-500',
  listVariant: 'customer',
  showViewStatusChange: false,
  formTitle: '✨ 소매 주문 등록',
  formSubtitle: '소매 고객 주문',
  formSectionTitle: '👤 고객 정보',
  formFields: [
    { label: '고객명 *', key: 'customer_name', placeholder: '예) 홍길동', col: 1 },
    { label: '연락처', key: 'contact', placeholder: '010-0000-0000', col: 1 },
    { label: '배송지 *', key: 'address', placeholder: '배송 주소를 입력해주세요', col: 2 },
  ],
  trackingHelpText: '송장 등록 시 손님이 마이페이지에서 실시간 배송조회를 할 수 있어요.',
  excelSheetName: '소매주문',
  excelFilePrefix: '소매주문',
  excelCustomerHeader: '고객명',
  excelIndentedRows: false,
  requireAddress: true,
  includeFadeStyle: false,
}

export default function RetailPage() {
  return <OrdersAdmin config={config} />
}
